on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build-anki-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install powershell-yaml
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -Force

      - name: Install MSIX Packaging Tool
        run: |
          New-Item -Type Directory -Name _build

          $Version = "v0.1.2"
          $Uri = "https://github.com/microsoft/win32-app-isolation/releases/download/$Version/ACP-MPT-$Version.zip"
          Invoke-WebRequest -Uri $Uri -OutFile .\_build\ACP-MPT-$Version.zip
          Expand-Archive -Path .\_build\ACP-MPT-$Version.zip -DestinationPath .\_build

          Import-Module -UseWindowsPowerShell Appx
          Add-AppxPackage -Path .\_build\MsixPackagingTool.msixbundle

      - name: Package the MSIX
        run: |
          New-Item -Type Directory -Name _build\msix-output
          $File = "templates\a\Anki\Anki\25.02\Anki.Anki_template.xml"
          .\scripts\Build-Msix.ps1 -TemplatePath $File -OutputPath .\_build\msix-output -Architecture x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msix
          path: |
            _build/msix-output

