on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build-msix:
    strategy:
      matrix:
        include:
          - package: anki
            version: "25.02"
            arch: x64
            template: templates\a\Anki\Anki\25.02\Anki.Anki_template.xml
          - package: freetube
            version: "0.23.1"
            arch: x64
            template: templates\p\PrestonN\FreeTube\0.23.1\PrestonN.FreeTube_template.xml
          - package: vim
            version: "9.1.1039"
            arch: x86
            template: templates\v\vim\vim\9.1.1039\vim.vim_template.xml
          - package: vim
            version: "9.1.1039"
            arch: x64
            template: templates\v\vim\vim\9.1.1039\vim.vim_template.xml
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell module cache
        uses: actions/cache@v4
        id: ps-cacher
        with:
          path: C:/Users/runneradmin/Documents/PowerShell/Modules
          key: ${{ runner.os }}-PowerShell-Dependencies

      - name: Install powershell-yaml
        if: steps.ps-cacher.outputs.cache-hit != 'true'
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -ErrorAction Stop

      - name: Setup MPT cache
        uses: actions/cache@v4
        id: mpt-cacher
        with:
          path: C:/Users/runneradmin/Documents/MPT
          key: ${{ runner.os }}-MPT-0.1.2

      - name: Download MSIX Packaging Tool
        if: steps.mpt-cacher.outputs.cache-hit != 'true'
        run: |
          $Version = "v0.1.2"
          $Uri = "https://github.com/microsoft/win32-app-isolation/releases/download/$Version/ACP-MPT-$Version.zip"
          $Zip = "C:\Users\runneradmin\Downloads\ACP-MPT-$Version.zip"
          $MPT = "C:\Users\runneradmin\Downloads\ACP-MPT-$Version"
          $MPTCache = "C:\Users\runneradmin\Documents\MPT"
          Invoke-WebRequest -Uri $Uri -OutFile $Zip
          Expand-Archive -Path $Zip -DestinationPath $MPT
          New-Item -Type Directory $MPTCache
          Move-Item -Path $MPT\MsixPackagingTool.msixbundle -Destination $MPTCache

      - name: Install MSIX Packaging Tool
        run: |
          Import-Module -UseWindowsPowerShell Appx
          Add-AppxPackage -Path C:\Users\runneradmin\Documents\MPT\MsixPackagingTool.msixbundle

      - name: Package the MSIX
        run: |
          New-Item -Type Directory -Name _build\msix-output
          $Params = @{
            TemplatePath = "${{ matrix.template }}"
            OutputPath = ".\_build\msix-output"
            Architecture = "${{ matrix.arch }}"
            Verbose = $true
          }
          .\scripts\Build-Msix.ps1 @Params

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.version }}-${{ matrix.arch }}-msix
          path: |
            _build/msix-output/*.msix

      - name: Upload template file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.version }}-${{ matrix.arch }}-template
          path: |
            _build/msix-output/*.xml
