on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build-msix:
    strategy:
      matrix:
        include:
          - package: anki
            version: "25.02"
            arch: x64
            template: templates\a\Anki\Anki\25.02\Anki.Anki_template.xml
          - package: freetube
            version: "0.23.1"
            arch: x64
            template: templates\p\PrestonN\FreeTube\0.23.1\PrestonN.FreeTube_template.xml
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install powershell-yaml
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -Force

      - name: Install MSIX Packaging Tool
        run: |
          New-Item -Type Directory -Name _build

          $Version = "v0.1.2"
          $Uri = "https://github.com/microsoft/win32-app-isolation/releases/download/$Version/ACP-MPT-$Version.zip"
          Invoke-WebRequest -Uri $Uri -OutFile .\_build\ACP-MPT-$Version.zip
          Expand-Archive -Path .\_build\ACP-MPT-$Version.zip -DestinationPath .\_build

          Import-Module -UseWindowsPowerShell Appx
          Add-AppxPackage -Path .\_build\MsixPackagingTool.msixbundle

      - name: Package the MSIX
        run: |
          New-Item -Type Directory -Name _build\msix-output
          $Params = @{
            TemplatePath = "${{ matrix.template }}"
            OutputPath = ".\_build\msix-output"
            Architecture = "${{ matrix.arch }}"
            Verbose = $true
          }
          .\scripts\Build-Msix.ps1 @Params

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.version }}-${{ matrix.arch }}-msix
          path: |
            _build/msix-output/*.msix

      - name: Upload template file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ matrix.version }}-${{ matrix.arch }}-template
          path: |
            _build/msix-output/*.yaml
